const PASSWORD='magetochikardari';
const STORAGE='matrixjournal.v1';
const DEFAULT_FEES={MES:{roundTurn:1.24,pointValue:5,tickSize:.25},MNQ:{roundTurn:1.24,pointValue:2,tickSize:.25},ES:{roundTurn:4.5,pointValue:50,tickSize:.25},NQ:{roundTurn:4.5,pointValue:20,tickSize:.25}};
const state={records:[],fees:{...DEFAULT_FEES},theme:'dark',density:'moderate',filter:'all',search:''};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function load(){const raw=localStorage.getItem(STORAGE); if(raw) Object.assign(state,JSON.parse(raw));}
function money(n){return (n<0?'-':'')+'$'+Math.abs(n||0).toFixed(2)}
function num(v,d=0){const n=parseFloat(String(v??'').replace(/[$,+]/g,''));return Number.isFinite(n)?n:d}
function uid(){return 'mj_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function section(text,name){const re=new RegExp(`\\[${name}\\]([\\s\\S]*?)(?=\\n\\[[A-Z_]+\\]|$)`,'i');return (text.match(re)?.[1]||'').trim()}
function kv(block){const o={};block.split(/\n/).forEach(l=>{const m=l.match(/^([^:#]+):\s*(.*)$/);if(m)o[m[1].trim().toLowerCase().replace(/\s+/g,'_')]=m[2].trim()});return o}
function parseTxt(text){
  const meta=kv(section(text,'META')); const thesis=section(text,'THESIS'); const management=section(text,'MANAGEMENT'); const outcome=section(text,'OUTCOME'); const lessons=section(text,'LESSONS');
  const execBlock=section(text,'EXECUTIONS'); const lines=execBlock.split(/\n/).map(l=>l.trim()).filter(Boolean);
  const executions=lines.map(line=>{const p=kv(line.replace(/\s*;\s*/g,'\n')); const inst=(p.instrument||meta.instrument||'UNKNOWN').toUpperCase(); const feeCfg=state.fees[inst.replace(/[A-Z]\d+$/,'')]||state.fees[inst]||{}; const qty=num(p.quantity||p.qty,1); const entry=num(p.entry_price||p.entry); const exit=num(p.exit_price||p.exit); const points=num(p.points,exit-entry); const gross=num(p.gross_pnl,points*(feeCfg.pointValue||1)*qty); const fees=p.fees?num(p.fees):num(feeCfg.roundTurn,0)*qty; return {id:uid(),trade:p.trade||'',instrument:inst,direction:p.direction||meta.direction||'Long',quantity:qty,submitted:p.order_submitted||p.submitted||'',entryPrice:entry,exitPrice:exit,exitType:p.exit_type||'',initialStop:p.initial_stop||'',points,ticks:p.ticks?num(p.ticks):feeCfg.tickSize?points/feeCfg.tickSize:0,grossPnl:gross,fees,netPnl:gross-fees,tags:(p.tags||'').split(',').map(s=>s.trim()).filter(Boolean)} });
  if(!executions.length) throw new Error('No executions found. Add an [EXECUTIONS] section with semicolon-separated fields.');
  return {id:uid(),createdAt:new Date().toISOString(),date:meta.date||new Date().toISOString().slice(0,10),title:meta.title||`${meta.setup||'Trade setup'} — ${meta.instrument||executions[0].instrument}`,setup:meta.setup||'',instrument:meta.instrument||executions[0].instrument,direction:meta.direction||executions[0].direction,quality:meta.setup_quality||meta.quality||'',thesis,management,outcome,lessons,tags:(meta.tags||'').split(',').map(s=>s.trim()).filter(Boolean),executions};
}
function totals(records=filteredRecords()){const ex=records.flatMap(r=>r.executions);const gross=ex.reduce((a,e)=>a+e.grossPnl,0),fees=ex.reduce((a,e)=>a+e.fees,0),net=gross-fees,wins=ex.filter(e=>e.netPnl>0),losses=ex.filter(e=>e.netPnl<0);return{records:records.length,trades:ex.length,gross,fees,net,wins:wins.length,losses:losses.length,winRate:ex.length?wins.length/ex.length*100:0,avgWin:wins.length?wins.reduce((a,e)=>a+e.netPnl,0)/wins.length:0,avgLoss:losses.length?losses.reduce((a,e)=>a+e.netPnl,0)/losses.length:0,points:ex.reduce((a,e)=>a+e.points,0),ticks:ex.reduce((a,e)=>a+e.ticks,0)}}
function filteredRecords(){return state.records.filter(r=>(state.filter==='all'||r.instrument===state.filter)&&JSON.stringify(r).toLowerCase().includes(state.search.toLowerCase()))}
function render(){document.body.className=`${state.theme} ${state.density}`;$('themeSelect').value=state.theme;$('densitySelect').value=state.density;renderFees();renderFilter();renderStats();renderChart();renderWarnings();renderRecords();renderEssays();save();}
function renderStats(){const t=totals();$('statsCards').innerHTML=[['Net P&L',money(t.net),t.net>=0?'good':'bad'],['Gross',money(t.gross),''],['Fees',money(t.fees),''],['Win rate',t.winRate.toFixed(1)+'%',''],['Trades',t.trades,''],['Points / ticks',`${t.points.toFixed(2)} / ${t.ticks.toFixed(0)}`,''],['Avg win',money(t.avgWin),'good'],['Avg loss',money(t.avgLoss),'bad']].map(c=>`<div class="stat-card"><span>${c[0]}</span><strong class="${c[2]}">${c[1]}</strong></div>`).join('')}
function renderChart(){const c=$('equityChart'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=180*devicePixelRatio;ctx.clearRect(0,0,w,h);const vals=[0];filteredRecords().flatMap(r=>r.executions).forEach(e=>vals.push(vals.at(-1)+e.netPnl));const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();ctx.strokeStyle='#22c55e';ctx.lineWidth=3*devicePixelRatio;ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1||1)*w,y=h-(v-min)/range*h*.8-h*.1;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke();}
function renderWarnings(){const t=totals(),w=[];if(!t.trades)w.push(['Start with one clean TXT import','Your dashboard becomes useful after three to five records.']);if(t.fees>Math.abs(t.gross)*.25&&t.trades)w.push(['Fees are consuming edge','Consider fewer, higher-quality executions or larger targets.']);if(t.winRate>60&&Math.abs(t.avgLoss)>t.avgWin)w.push(['High win rate, weak payoff','Your losers are larger than winners; protect downside.']);if(t.losses>=3)w.push(['Loss cluster detected','Review whether losses came from one setup, time of day, or emotional state.']);if(t.trades>0&&t.net>0)w.push(['Positive expectancy window','Keep documenting context so you can identify repeatable conditions.']);$('warningCount').textContent=w.length;$('warnings').innerHTML=w.map(x=>`<div class="insight"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function renderRecords(){const tpl=$('recordTemplate');$('records').innerHTML='';filteredRecords().slice().reverse().forEach(r=>{const node=tpl.content.cloneNode(true),card=node.querySelector('.record-card'),head=node.querySelector('.record-head'),body=node.querySelector('.record-body'),t=totals([r]);head.innerHTML=`<span><strong>${r.date} · ${r.title}</strong><br><small class="muted">${r.setup||'Setup'} · ${r.executions.length} execution(s)</small></span><span class="${t.net>=0?'good':'bad'}">${money(t.net)}</span>`;body.innerHTML=`<p><strong>Thesis:</strong> ${r.thesis||'—'}</p><p><strong>Management:</strong> ${r.management||'—'}</p><p><strong>Outcome:</strong> ${r.outcome||'—'}</p><p><strong>Lessons:</strong> ${r.lessons||'—'}</p>${execTable(r.executions)}<button class="danger" data-del="${r.id}">Delete record</button>`;head.onclick=()=>card.classList.toggle('open');$('records').appendChild(node)});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this record?')){state.records=state.records.filter(r=>r.id!==b.dataset.del);render()}})}
function execTable(ex){return `<table class="exec-table"><tr><th>Trade</th><th>Instrument</th><th>Dir</th><th>Qty</th><th>Entry</th><th>Exit</th><th>Points</th><th>Gross</th><th>Fees</th><th>Net</th></tr>${ex.map(e=>`<tr><td>${e.trade}</td><td>${e.instrument}</td><td>${e.direction}</td><td>${e.quantity}</td><td>${e.entryPrice}</td><td>${e.exitPrice}</td><td>${e.points.toFixed(2)}</td><td>${money(e.grossPnl)}</td><td>${money(e.fees)}</td><td class="${e.netPnl>=0?'good':'bad'}">${money(e.netPnl)}</td></tr>`).join('')}</table>`}
function renderFilter(){const instruments=[...new Set(state.records.map(r=>r.instrument))];$('instrumentFilter').innerHTML='<option value="all">All instruments</option>'+instruments.map(i=>`<option ${state.filter===i?'selected':''}>${i}</option>`).join('')}
function renderFees(){$('feeEditor').innerHTML=Object.entries(state.fees).map(([k,v])=>`<div class="fee-row"><input value="${k}" data-fee-key="${k}"><input value="${v.roundTurn}" data-fee-val="${k}" type="number" step="0.01" title="Round-turn fee"></div>`).join('')}
function renderEssays(){const topics=['Revenge trading','Early exits','FOMO entries','Oversizing','Hesitation','Moving stops','Cutting winners','News risk','Overtrading','Rule drift','Good loss','Boredom trades','Confidence spike','Drawdown reset','Process focus','Target discipline','Chasing neckline','Scaling limits','Risk-free exits','Session review'];$('essayLibrary').innerHTML=Array.from({length:200},(_,i)=>{const topic=topics[i%topics.length];return `<article class="essay"><strong>${i+1}. ${topic}</strong><p>${topic} improves when you write the trigger, the rule you followed or broke, and one specific next-session constraint. Grade the behavior, not only the P&L.</p></article>`}).join('')}
function toXml(){const esc=s=>String(s??'').replace(/[<>&'"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]));return `<?xml version="1.0"?><matrixJournal>${state.records.map(r=>`<record id="${r.id}" date="${esc(r.date)}"><title>${esc(r.title)}</title><setup>${esc(r.setup)}</setup><thesis>${esc(r.thesis)}</thesis><management>${esc(r.management)}</management><outcome>${esc(r.outcome)}</outcome><lessons>${esc(r.lessons)}</lessons><executions>${r.executions.map(e=>`<execution instrument="${esc(e.instrument)}" direction="${esc(e.direction)}"><quantity>${e.quantity}</quantity><entry>${e.entryPrice}</entry><exit>${e.exitPrice}</exit><points>${e.points}</points><gross>${e.grossPnl}</gross><fees>${e.fees}</fees><net>${e.netPnl}</net></execution>`).join('')}</executions></record>`).join('')}</matrixJournal>`}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function importRecord(text){const r=parseTxt(text);state.records.push(r);render();alert('Imported '+r.title)}
$('loginForm').onsubmit=e=>{e.preventDefault();if($('username').value==='admin'&&$('password').value===PASSWORD){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');sessionStorage.setItem('mj.unlocked','1');render()}else $('loginError').textContent='Invalid local credentials.'};
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('mj.unlocked');location.reload()};$('themeSelect').onchange=e=>{state.theme=e.target.value;render()};$('densitySelect').onchange=e=>{state.density=e.target.value;render()};$('instrumentFilter').onchange=e=>{state.filter=e.target.value;render()};$('searchInput').oninput=e=>{state.search=e.target.value;render()};$('parsePasteBtn').onclick=()=>importRecord($('txtPaste').value);$('txtFile').onchange=e=>e.target.files[0]?.text().then(importRecord);$('exportJsonBtn').onclick=()=>download('matrixjournal.json',JSON.stringify(state,null,2),'application/json');$('exportXmlBtn').onclick=()=>download('matrixjournal.xml',toXml(),'text/xml');$('resetBtn').onclick=()=>{if(confirm('Are you sure? You will lose your XML/JSON data. Download it before resetting.')){state.records=[];save();render()}};$('saveFeesBtn').onclick=()=>{const next={};document.querySelectorAll('[data-fee-key]').forEach(inp=>{const k=inp.value.toUpperCase();const old=state.fees[inp.dataset.feeKey]||{};next[k]={...old,roundTurn:num(document.querySelector(`[data-fee-val="${inp.dataset.feeKey}"]`).value)}});state.fees=next;render()};$('dataImport').onchange=e=>e.target.files[0]?.text().then(text=>{if(e.target.files[0].name.endsWith('.json'))Object.assign(state,JSON.parse(text));else alert('XML import is documented for backend migration; export is available in this static MVP.');render()});
load(); if(sessionStorage.getItem('mj.unlocked')){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden')} render();
